ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "@upleveled/*"
  - eslint-config-upleveled
  - stylelint-config-upleveled

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

strictDepBuilds: true
