allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: false

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled
